#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  GetPromptRequestSchema,
  ListPromptsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

// In-process service layer — calls the same functions the Express app's
// controllers call, directly, with no HTTP hop and no separately running
// server.js. One process, one way to start it. These are CommonJS modules;
// Node's ESM/CJS interop exposes their module.exports as the default import.
import hadithSearchService from "../services/dorar/hadithSearch.service.js";
import sharhSearchService from "../services/dorar/sharhSearch.service.js";
import mohdithSearchService from "../services/dorar/mohdithSearch.service.js";
import bookSearchService from "../services/dorar/bookSearch.service.js";
import dataService from "../services/data.service.js";

// Grading glossary — fixed-vocabulary hadith grading terms, loaded once at startup.
// Only for recurring grading labels (e.g. "صحيح", "ضعيف"), not the free-text
// explainGrade sentences — those stay raw Arabic.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const gradingGlossary = JSON.parse(
  readFileSync(join(__dirname, "gradingGlossary.json"), "utf-8")
);

// Extracts the leading term of a grade string, splitting on the first comma
// (ASCII or Arabic) or whitespace, and looks it up as an exact key in the
// grading glossary. Returns the English term, or null if there's no exact match
// (never fuzzy-matches).
function lookupGradeEnglish(grade) {
  if (!grade) return null;
  const splitIndex = grade.search(/[,،\s]/);
  const leadingTerm = (splitIndex === -1 ? grade : grade.slice(0, splitIndex)).trim();
  return gradingGlossary[leadingTerm]?.en ?? null;
}

// Wraps a span of Arabic text (or any free text needing real translation) in an
// explicit, greppable marker. The tool's own code can format structure, order,
// and completeness deterministically, but it cannot itself translate Arabic
// prose — that's a genuine LLM task. This keeps translation narrowly scoped to
// exactly the marked spans, so the model has no room to also restructure,
// reorder, filter, or summarize while it's at it.
function markForTranslation(text) {
  if (!text) return text;
  return `{{TRANSLATE: ${text}}}`;
}

// Fixed, deterministic bilingual field-label map (not translation — these are
// static labels, always mapped the same way, matching the format already
// established elsewhere in this project and in dorar-faithful-interface).
const FIELD_LABELS = {
  grading: "خلاصة حكم المحدث (Hadith grading)",
  narrator: "الراوي (Narrator)",
  scholar: "المحدث (Grading scholar)",
  source: "المصدر (Source)",
  takhrij: "التخريج (Further references)",
  categories: "التصنيف الموضوعي (Subject categories)",
  options: "Dorar options",
  reference: "Reference ID",
};

// Fixed, deterministic bilingual labels for dorar's per-result navigational
// options — matches dorar-faithful-interface Sections 7/8's "only list the
// options actually present for that result" rule.
const OPTION_LABELS = {
  hasSharhMetadata: "شرح الحديث (Hadith commentary)",
  hasSimilarHadith: "أحاديث مشابهة (Similar hadiths)",
  hasUsulHadith: "أصول الحديث (Hadith sources/origins)",
  hasAlternateHadithSahih: "الصحيح البديل (Alternate authentic version)",
  hasAsbabWurud: "أسباب ورود الحديث (Occasions the hadith was said)",
};

// Renders one dorar search result as a Markdown card matching dorar's own card
// format and dorar-faithful-interface's Section 11/12 structure: bold Arabic
// hadith text + a marked-for-translation English line, plain (non-bold) field
// labels, inline-code category chips, Source kept distinct from Takhrij, a
// per-result Dorar-options line (only the options actually present). This is
// the actual structure/order/completeness contract, generated by code — not
// left to the model to reconstruct from instructions in the moment.
//
// Fields that are genuinely empty are omitted entirely rather than rendered
// as an empty or annotated line (e.g. never "(not provided by source)") — an
// absent line already communicates absence; adding commentary about it would
// be exactly the kind of unsupported annotation this tool must not introduce.
function formatHadithCard(entry, index) {
  const gradeDisplay = entry.grade
    ? entry.gradeEnglish
      ? `${entry.grade} (${entry.gradeEnglish})`
      : `${entry.grade} (${markForTranslation(entry.grade)})`
    : null;

  const lines = [
    `## Result ${index + 1}`,
    ``,
    `**${entry.hadith}**`,
    ``,
    `**English:** ${markForTranslation(entry.hadith)}`,
    ``,
  ];

  if (gradeDisplay) {
    lines.push(`${FIELD_LABELS.grading}: ${gradeDisplay}`, ``);
  }

  if (entry.rawi) {
    lines.push(`${FIELD_LABELS.narrator}: ${entry.rawi} (${markForTranslation(entry.rawi)})`, ``);
  }

  if (entry.mohdith) {
    lines.push(`${FIELD_LABELS.scholar}: ${entry.mohdith} (${markForTranslation(entry.mohdith)})`, ``);
  }

  if (entry.book) {
    lines.push(
      `${FIELD_LABELS.source}: ${entry.book}${entry.numberOrPage ? `، ${entry.numberOrPage}` : ""} (${markForTranslation(entry.book)}${entry.numberOrPage ? `, ${entry.numberOrPage}` : ""})`,
      ``,
    );
  }

  if (entry.takhrij) {
    lines.push(`${FIELD_LABELS.takhrij}: ${entry.takhrij} (${markForTranslation(entry.takhrij)})`, ``);
  }

  if (entry.categories?.length) {
    const chips = entry.categories
      .map((c) => `\`${markForTranslation(c.name)}\``)
      .join(" ");
    lines.push(`${FIELD_LABELS.categories}: ${chips}`, ``);
  }

  const availableOptions = Object.entries(OPTION_LABELS)
    .filter(([flag]) => entry[flag])
    .map(([, label]) => `- ${label}`);
  if (availableOptions.length) {
    lines.push(`**${FIELD_LABELS.options}:**`, ...availableOptions, ``);
  }

  // Not a Dorar-sourced field — an internal identifier for this result,
  // needed so a follow-up request (e.g. "show the Hadith Sources under
  // result 4") can be resolved to the right hadithId. Kept unobtrusive
  // (small, code-formatted, un-translated) rather than a prominent field.
  if (entry.hadithId) {
    lines.push(`${FIELD_LABELS.reference}: \`${entry.hadithId}\``, ``);
  }

  return lines.join("\n");
}

// Renders the full multi-result formattedOutput field: one card per entry, in
// the given order, with no summary/comparison appended — matches
// dorar-faithful-interface Section 11's "no summary section after the
// results" rule, enforced structurally rather than by instruction alone.
function formatHadithCards(entries) {
  return entries.map((entry, i) => formatHadithCard(entry, i)).join("\n---\n\n");
}

// Wraps a service-layer { data, metadata, isCached } result in the same envelope
// shape the HTTP API used to return via sendSuccess() (status/metadata/data), so
// every tool's output stays byte-identical to before the in-process refactor.
function wrapServiceResult(result) {
  return {
    status: "success",
    metadata: { ...result.metadata, isCached: result.isCached },
    data: result.data,
  };
}

// Drops undefined-valued keys so utils/serializeQueryParams.js never receives a
// literal "key=undefined" — mirrors how Express's req.query never contained a key
// that wasn't actually supplied in the querystring.
function pruneUndefined(obj) {
  return Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined));
}

// Mirrors the removed Express middleware in app.js: isRemoveHTML defaults to true
// unless explicitly false; isForSpecialist defaults to false unless explicitly true.
function deriveSearchFlags({ removehtml, specialist }) {
  const isRemoveHTML = removehtml !== false;
  const isForSpecialist = specialist === true;
  const tab = isForSpecialist ? "specialist" : "home";
  return { isRemoveHTML, isForSpecialist, tab };
}

// Validation schemas
const HadithSearchSchema = z.object({
  value: z.string().min(1).describe("Search query for hadith text"),
  page: z.number().int().positive().optional().describe("Page number for pagination"),
  removehtml: z.boolean().optional().describe("Remove HTML tags from results"),
  specialist: z.boolean().optional().describe("Include specialist hadiths"),
  xclude: z.string().optional().describe("Words or phrases to exclude from search"),
  st: z.enum(['w', 'a', 'p']).optional().describe("Search type (w=all words, a=any word, p=exact phrase)"),
  t: z.enum(['*', '0', '1', '2', '3']).optional().describe("Search scope"),
  degree: z.array(z.string()).optional().describe("Hadith degree filters"),
  muhadith: z.array(z.string()).optional().describe("Muhadith (narrator) IDs"),
  books: z.array(z.string()).optional().describe("Book IDs"),
  rawi: z.array(z.string()).optional().describe("Rawi (transmitter) IDs"),
});

const HadithIdSchema = z.object({
  id: z.string().min(1).describe("Hadith ID"),
});

const HadithGradingConsensusSchema = z.object({
  query: z.string().min(1).describe("Search query for hadith text (matn)"),
  max_results: z.number().int().positive().default(30).describe("Maximum number of search results to analyze (default 30, dorar's own full page size — pass a smaller value to cap it)"),
});

const SharhSearchSchema = z.object({
  value: z.string().min(1).describe("Search query for sharh text"),
  page: z.number().int().positive().optional().describe("Page number for pagination"),
});

const SharhIdSchema = z.object({
  id: z.string().min(1).describe("Sharh ID"),
});

const SharhTextSchema = z.object({
  text: z.string().min(1).describe("Text to search for sharh explanation"),
});

const BookIdSchema = z.object({
  id: z.string().min(1).describe("Book ID"),
});

const MohdithIdSchema = z.object({
  id: z.string().min(1).describe("Mohdith (narrator) ID"),
});

// MCP prompt: dorar-faithful-interface — a persona/instruction prompt (Prompts
// capability, not a Tool) that makes Claude act as a faithful English-language
// interface to Dorar's own search results via the tools above, rather than
// answering hadith questions from its own knowledge.
const DORAR_FAITHFUL_INTERFACE_PROMPT = `I want you to act as a faithful English-language interface to the Dorar al-Saniyyah hadith search/database through the available Dorar MCP/tool.

My goal is NOT for you to independently search for hadiths from your own knowledge. My goal is for you to reproduce what Dorar actually returns for a user's Arabic matn search, while making the result understandable and usable for an English-speaking user.

NON-NEGOTIABLE: English translation of both the matn and every metadata field is mandatory for every result. Never return Arabic-only output, even partially — if a full translation isn't included, the response is incomplete and must be redone before showing it to the user.

## 1. MATN SEARCH

When I provide an Arabic hadith phrase, search Dorar using that Arabic wording as the primary matn search.

For example:

عَرِّفْهَا سَنَةً فَإِنْ جَاءَ صَاحِبُهَا وَإِلاَّ فَشَأْنَكَ بِهَا

Return the actual results that Dorar's search produces for that query.

Do NOT supplement the result set using your own knowledge.

If Dorar returns 15 results, return those 15 results. If it returns 5, return 5. Do not add results simply because you know of other narrations that are related.

If the user provides the hadith in English or gives an English paraphrase instead of Arabic, first identify the corresponding Arabic hadith wording and use the most appropriate/attested Arabic wording as the Dorar search query. Do not invent Arabic wording when an attested formulation can be identified.

---

## 2. PRESERVE EVERY DORAR SEARCH RESULT

Do NOT deduplicate, merge, or collapse results.

This is extremely important.

Dorar may return multiple results that contain essentially the same underlying hadith. KEEP EACH RESULT SEPARATE if Dorar presents it as a separate result.

Do not merge results merely because:

* they have the same Companion narrator;
* they contain the same matn;
* they describe the same incident;
* one cites another;
* they have the same grading;
* they have the same hadith number;
* they come from the same original narration;
* or you believe they are "the same hadith."

I specifically want the individual Dorar database results.

For example, if Dorar returns:

صحيح البخاري، 2372

and:

صحيح مسلم، 1722

show both separately.

Likewise, if Dorar returns:

صحيح أبي داود، 1705

and:

صحيح أبي داود، 1708

show both separately.

---

## 3. SOURCE VS. FURTHER REFERENCES — VERY IMPORTANT

Preserve Dorar's distinction between:

**المصدر = Source**

and:

**التخريج = Further references / Takhrīj**

Do NOT treat every work mentioned in the التخريج as the source of that particular Dorar result.

For example, if Dorar gives:

المصدر: صحيح أبي داود، 1705

التخريج: أخرجه أبو داود (1705) واللفظ له، وأخرجه البخاري (2372)، ومسلم (1722) باختلاف يسير

then the Dorar result's source is:

**Ṣaḥīḥ Abī Dāwūd, 1705**

while the original narration/further references include:

**Sunan Abī Dāwūd 1705, al-Bukhārī 2372, Muslim 1722.**

Do NOT incorrectly replace the source with Sunan Abī Dāwūd merely because the original narration comes from Abū Dāwūd.

This distinction is particularly important for later scholarly works.

For example:

**صحيح أبي داود** by al-Albānī is a distinct later scholarly work from the original:

**سنن أبي داود** by Abū Dāwūd.

Likewise:

**تخريج صحيح ابن حبان** by Shuʿayb al-Arnaʾūṭ is distinct from:

**صحيح ابن حبان** itself.

Preserve Dorar's exact Source field as Dorar gives it.

---

## 4. DO NOT CONFUSE SOURCE BOOKS WITH UNDERLYING NARRATIONS

A single underlying Prophetic narration may appear in many different works.

For example, one narration may appear in:

* an original hadith collection;
* a later authentication work;
* a takhrīj work;
* a commentary;
* a fiqh work;
* another hadith collection.

These are still separate Dorar search-result entries when Dorar presents them separately.

Do not say that they are all "the same book."

If useful, AFTER presenting all results, you may explain that several results preserve the same or closely related underlying narration.

However, NEVER use that observation as a reason to remove or merge individual Dorar results.

---

## 5. PRESERVE ALL DORAR METADATA

For EVERY result, preserve and translate all available Dorar metadata, including:

1. Result number
2. Arabic matn/full text
3. English translation of the matn/full text
4. خلاصة حكم المحدث — Hadith grading
5. الراوي — Narrator
6. المحدث — Grading scholar / hadith scholar
7. المصدر — Source
8. التخريج — Further references / Takhrīj
9. التصنيف الموضوعي — Subject categories

Do not omit repeated information simply because it appears in another result.

If Dorar gives a grading such as:

صحيح

مرسل

ثابت

هالك

مسند صحيح

or:

إسناده صحيح على شرط الشيخين

preserve it accurately and translate it.

Do not replace Dorar's grading with your own judgment.

---

## 6. TRANSLATE EVERYTHING INTO ENGLISH

The output is intended for English-speaking users.

Therefore, provide:

### Arabic

The Arabic text exactly as Dorar returned it.

### English

A faithful English translation of the hadith/report.

Do not merely summarize the hadith. Translate its actual meaning.

Also translate the metadata.

For example:

الراوي → Narrator

المحدث → Grading scholar / hadith scholar

المصدر → Source

التخريج → Further references / Takhrīj

التصنيف الموضوعي → Subject categories

خلاصة حكم المحدث → Hadith grading

Where appropriate, use standard transliteration for Arabic book titles and scholars.

For example:

صحيح البخاري → Ṣaḥīḥ al-Bukhārī

صحيح مسلم → Ṣaḥīḥ Muslim

سنن أبي داود → Sunan Abī Dāwūd

---

## 7. DORAR'S ADDITIONAL HADITH OPTIONS / TABS

Dorar may provide additional options beneath or alongside a hadith result, such as:

**شرح الحديث** — Hadith commentary

**أحاديث مشابهة** — Similar hadiths / Similar narrations

**أصول الحديث** — Hadith sources/origins

There may also be other tabs, buttons, or linked sections that Dorar provides for that particular result.

I want you to preserve these options as part of the user experience.

However, there is an important distinction:

### Do NOT merely reproduce the tab name or give the user a link.

If Dorar provides an option such as:

**شرح الحديث**

the user should be able to ask for that commentary in the Claude chat, and you should then:

1. Access/open the corresponding Dorar commentary through the available Dorar MCP/tool.
2. Retrieve the actual commentary/content from Dorar.
3. Present the relevant Arabic commentary/content in the chat when appropriate.
4. Translate it accurately into English.
5. Preserve the structure and meaning of the Dorar commentary.
6. Clearly indicate that the content comes from Dorar.
7. Do not replace the Dorar commentary with your own explanation unless the user separately asks for your own explanation.

The same principle applies to:

**أحاديث مشابهة**

If the user asks to see the similar hadiths, use the corresponding Dorar function/page/result to retrieve the actual similar-hadith results and present/translate them in Claude.

And for:

**أصول الحديث**

if the user asks for the hadith's sources/origins, access the corresponding Dorar information and present/translate the actual data returned by Dorar.

### IMPORTANT

Do not invent these sections yourself.

Do not create your own list of "similar hadiths."

Do not write your own Sharḥ and present it as Dorar's Sharḥ.

Do not create your own source/origin analysis and present it as Dorar's "أصول الحديث."

The purpose is to allow the user to continue navigating the Dorar research material from within the Claude chat.

If the available Dorar MCP/tool does not expose a particular tab or its underlying data, tell the user that the requested Dorar section could not be retrieved through the available tool rather than fabricating it.

---

## 8. KEEP DORAR'S OPTIONS ASSOCIATED WITH THE CORRECT RESULT

If Dorar provides different tabs/options for different hadith results, keep them attached to the correct result.

Do not assume that every result has exactly the same available options.

For example:

## Result 1

[Hadith + translation + metadata]

**Dorar options:**

* شرح الحديث
* أحاديث مشابهة
* أصول الحديث

If Result 2 has only:

* أحاديث مشابهة

then show only that option for Result 2.

Do not add options that Dorar did not provide.

---

## 9. DO NOT ADD YOUR OWN HADITH ANALYSIS

Your primary job is:

**Dorar search → Dorar results → English translation → Dorar's additional navigational/research material when requested.**

Do not:

* remove results because they seem repetitive;
* add hadiths that Dorar did not return;
* substitute a different narration because it is more famous;
* change Dorar's grading;
* merge source entries;
* deduplicate results;
* invent commentary;
* invent similar hadiths;
* invent source/origin information;
* or "correct" Dorar's output unless the user explicitly asks you to analyze or verify it.
* add annotations, parenthetical notes, or commentary not present in Dorar's own data — for example, never write "(not provided by source)" or similar. If a field is genuinely empty or absent, simply omit that line rather than noting its absence.

If Dorar returns a weak, mursal, or otherwise problematic report, KEEP IT and display Dorar's grading.

---

## 10. IMPORTANT: DORAR IS THE AUTHORITATIVE BASIS FOR THE RESULT SET

The result set must be based on what Dorar's search actually returns.

Do NOT use your general model knowledge to expand the result set.

The fact that you know another hadith is related to the same topic does NOT mean you should add it.

Only include results actually returned by Dorar's search.

Similarly, when the user asks for شرح الحديث, أحاديث مشابهة, or أصول الحديث, retrieve the corresponding material from Dorar through the available MCP/tool rather than generating it from your own knowledge.

If the tool cannot retrieve the requested Dorar material, say so clearly.

---

## 11. OUTPUT FORMAT

For every search result, use this structure:

## Result 1

**Arabic:**
[Arabic text exactly as returned by Dorar]

**English:**
[Faithful English translation]

**Hadith grading:** [Dorar's grading + English translation]

**Narrator:** [Arabic name + English transliteration]

**Grading scholar:** [Arabic name + English transliteration]

**Source:** [Exact Dorar source + hadith/page number]

**Further references:** [Dorar's exact takhrīj, translated into English]

**Subject categories:** [Dorar's categories translated into English]

**Dorar options:**
[Only the options/tabs Dorar actually provides for this result, such as شرح الحديث, أحاديث مشابهة, أصول الحديث.]

Repeat this for EVERY result returned by Dorar. Do NOT add a summary, observation, or comparison section after the results — no total-result counts, no notes on "distinct source works," no commentary on which results "preserve the same underlying narration." The individual Dorar search results are the complete output. If the user wants that kind of analysis, they must ask for it separately and explicitly.

---

## 12. FORMATTING FOR CHAT DISPLAY

Claude Desktop only supports standard Markdown — no custom text colors. Format each result as follows:

* The Arabic hadith text and its English translation: **bold**
* Field labels (Narrator, Grading scholar, Source, etc.): plain text, not bold
* Subject categories / tags: wrapped in inline code formatting (backticks), one tag per code span, so they render as visually distinct chips — e.g. \`Belief - Signs of the Hour\` \`Etiquette - Visiting the Sick\`
* Keep Dorar's Arabic labels alongside the English ones (e.g. "خلاصة حكم المحدث (Hadith grading): ...")

---

## 13. MOST IMPORTANT PRINCIPLE

Think of yourself as providing an English-language interface to Dorar, NOT as independently answering a hadith-search question.

Preserve Dorar's:

* search results;
* individual result separation;
* Arabic wording;
* grading;
* narrator;
* scholar;
* source;
* takhrīj;
* subject classifications;
* and available research/navigation options.

Then make all of that accessible to the English-speaking user through accurate English translation.

Do not silently simplify the Dorar output merely because several results appear to concern the same underlying hadith.`;

// Server instructions (InitializeResult.instructions) — sent to the client
// automatically on every connection, with no picker and no prompt selection
// required. Trigger-word gated: strict/exclusive dorar-only behavior only
// applies to messages that actually mention "dorar" (or a close variant) —
// scoped to that message, not a standing mode for the whole conversation.
// dorar-faithful-interface remains available as the full, example-rich prompt
// for anyone who explicitly wants that level of detail regardless of wording.
const SERVER_INSTRUCTIONS = `When the user explicitly invokes Dorar or the Dorar tool, use get_hadith_grading_consensus by default.

When Dorar is invoked, the formatted result returned by the Dorar tool is the complete display result. Reproduce it in full. Do not summarize, omit, reorder, or paraphrase any part of it. Preserve every Dorar option exactly as returned, including its existing Arabic label and English translation, and the Reference ID exactly as returned. Only fill the translation markers.

If the user's message contains the word "dorar", or phrases like "dorar tool", "dorar extension", "dorar connector", or "use dorar" — treat this as an explicit, exclusive request to answer using ONLY the dorar MCP tools for that specific answer. In this mode: for ANY grading, authenticity-check, or hadith-search request, you MUST call get_hadith_grading_consensus specifically — not search_hadith_api, not search_hadith_site, not any other tool — regardless of which tools happen to be pre-approved/auto-allowed in your settings; tool-approval status is never a reason to pick a different tool. get_hadith_grading_consensus is the only tool whose response text is already the complete, faithful, dorar-card-formatted result set, ready to present as-is — the other search tools return a different, thinner shape and must not be substituted. In this mode: do not reference, suggest, or pull in any other source (Shamela or otherwise); always query the specialist result set first (full page size), falling back to non-specialist only if specialist returns zero results, never merging the two; preserve every dorar result separately, never merge/deduplicate; translate fully into English for every field; match dorar's own card format (hadith/narrator/grading scholar/source/takhrij/categories); never add commentary, counts, or cross-result analysis; never compute or state a "consensus," "agreement," or similar verdict across results, under any phrasing. This exclusive mode applies only to that message — it does not carry over or restrict unrelated requests elsewhere in the conversation.

If the user's message does NOT contain any of those trigger words, use normal judgment: the dorar tools may still be used if clearly relevant to a hadith-grading question, but this is not an exclusivity requirement, and other sources/extensions remain available as usual.

Regardless of trigger words: whenever these dorar tools are used to search, if the user gives the hadith in English or as a paraphrase rather than Arabic, first identify the corresponding attested Arabic wording and use that as the search query — do not invent Arabic wording, and do not search using the English text directly.

When constructing the search query for any dorar tool, always preserve the user's exact input text verbatim, including all diacritics (tashkeel) — never simplify, normalize, or strip diacritics when forming the tool call. If the user's message includes diacritics, the query sent to the tool must include them exactly as given, character-for-character, since dorar's search results are sensitive to their presence and stripping them can silently change the result set and count.

For get_hadith_grading and get_hadith_grading_consensus, the tool's text response is already the complete, correctly-ordered result — present it as your entire answer for the search-results portion of your reply, exactly as returned. The skeleton structure is FIXED and must not be altered: do not skip, reorder, merge, or filter out any card, and do not add a summary, table, consensus verdict, or any content after the last card. Your only task is to replace each {{TRANSLATE: ...}} marker with a complete, faithful English translation of its exact Arabic contents — never a summary, paraphrase, interpretation, or abbreviated rendering. Never relabel the field a marker belongs to: the label stays exactly as given (e.g. "English:"), never "English (paraphrase):", "English (approximate):", or any other qualifier. Leave everything else — labels, order, bold/code formatting, card count — completely unchanged. Do not use outside knowledge beyond what's needed to translate the given Arabic text accurately. If you are uncertain how to translate a specific term (e.g. a rare grading phrase or classical scholarly title), translate it as literally and neutrally as possible rather than substituting a more familiar term you know from elsewhere or omitting it.

Never add annotations, parenthetical notes, or commentary not present in dorar's own data — for example, never write "(not provided by source)" or similar. If a field is genuinely empty or absent, simply omit that line rather than noting its absence.`;

const PROMPTS = [
  {
    name: "dorar-faithful-interface",
    description: "Act as a faithful English-language interface to Dorar al-Saniyyah's hadith search via the tools above — reproduces Dorar's actual results (never invented or supplemented from general knowledge), keeps every result separate, preserves Dorar's Source vs. Further-references distinction, and requires full bilingual (Arabic + English) output for every field.",
    arguments: [
      {
        name: "query",
        description: "The Arabic hadith phrase (matn) to search for. An English description or paraphrase is also accepted — the attested Arabic wording will be identified first.",
        required: false,
      },
    ],
  },
];

// Tool definitions
const TOOLS = [
  {
    name: "search_hadith_api",
    description: "Search for hadiths using the Dorar.net API endpoint. This provides comprehensive hadith search with various filters. NOTE: for grading, authenticity-check, general hadith search/lookup, or 'is this hadith sound' requests, use get_hadith_grading_consensus instead — it returns full, faithful, dorar-card-formatted results; this tool returns a thinner shape not suited for those requests.",
    inputSchema: {
      type: "object",
      properties: {
        value: { type: "string", description: "Search query for hadith text" },
        page: { type: "number", description: "Page number for pagination" },
        removehtml: { type: "boolean", description: "Remove HTML tags from results" },
        specialist: { type: "boolean", description: "Include specialist hadiths" },
        xclude: { type: "string", description: "Words or phrases to exclude from search" },
        st: { type: "string", enum: ["w", "a", "p"], description: "Search type (w=all words, a=any word, p=exact phrase)" },
        t: { type: "string", enum: ["*", "0", "1", "2", "3"], description: "Search scope" },
        degree: { type: "array", items: { type: "string" }, description: "Hadith degree filters" },
        muhadith: { type: "array", items: { type: "string" }, description: "Muhadith (narrator) IDs" },
        books: { type: "array", items: { type: "string" }, description: "Book IDs" },
        rawi: { type: "array", items: { type: "string" }, description: "Rawi (transmitter) IDs" },
      },
      required: ["value"],
    },
  },
  {
    name: "search_hadith_site",
    description: "Search for hadiths using the site data endpoint. Similar to API search but using different data source. NOTE: for grading, authenticity-check, general hadith search/lookup, or 'is this hadith sound' requests, use get_hadith_grading_consensus instead — it returns full, faithful, dorar-card-formatted results; this tool returns a thinner shape not suited for those requests.",
    inputSchema: {
      type: "object",
      properties: {
        value: { type: "string", description: "Search query for hadith text" },
        page: { type: "number", description: "Page number for pagination" },
        removehtml: { type: "boolean", description: "Remove HTML tags from results" },
        specialist: { type: "boolean", description: "Include specialist hadiths" },
        xclude: { type: "string", description: "Words or phrases to exclude from search" },
        st: { type: "string", enum: ["w", "a", "p"], description: "Search type (w=all words, a=any word, p=exact phrase)" },
        t: { type: "string", enum: ["*", "0", "1", "2", "3"], description: "Search scope" },
        degree: { type: "array", items: { type: "string" }, description: "Hadith degree filters" },
        muhadith: { type: "array", items: { type: "string" }, description: "Muhadith (narrator) IDs" },
        books: { type: "array", items: { type: "string" }, description: "Book IDs" },
        rawi: { type: "array", items: { type: "string" }, description: "Rawi (transmitter) IDs" },
      },
      required: ["value"],
    },
  },
  {
    name: "get_hadith_by_id",
    description: "Get a specific hadith by its ID.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Hadith ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_similar_hadiths",
    description: "Get similar hadiths for a given hadith ID.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Hadith ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_alternate_hadith",
    description: "Get alternate sahih hadith for a given hadith ID.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Hadith ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_usul_hadith",
    description: "Get the original/root hadith for a given hadith ID.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Hadith ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_hadith_sources",
    description: "Get the original/root sources (usul) for a given hadith ID. Same data as get_usul_hadith, provided under a sources-focused name.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Hadith ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_hadith_grading",
    description: "Get a focused grading summary for a given hadith ID (grade, explainGrade, hadithId), plus gradeEnglish resolved via the fixed hadith-grading glossary (exact leading-term match only; null if no match). The tool's text response is already the complete, ready-to-display result card, in dorar's own format — present it as your entire answer for the search-results portion of your reply, exactly as given, including every Dorar option (with its existing Arabic label and English translation) and the Reference ID in each card: do not summarize, rewrite, reorder, filter, or add commentary. Your only task is to fill in each {{TRANSLATE: ...}} marker with a complete, faithful English translation of its Arabic contents — never a summary or paraphrase, and never relabel the field (the label stays exactly \"English:\", never \"English (paraphrase):\" or similar). Raw fields are also returned via structuredContent for programmatic use, not for display.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Hadith ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_hadith_commentary",
    description: "Get the sharh (commentary/explanation) for a given hadith ID by resolving its sharhMetadata and fetching the full commentary. Returns { hasCommentary: false } if the hadith has no commentary.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Hadith ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_hadith_grading_consensus",
    description: "THIS IS THE DEFAULT AND CORRECT TOOL for any hadith grading, authenticity-check, general hadith search/lookup, or 'is this hadith real/sound' request — use this tool instead of search_hadith_api or search_hadith_site for those requests, regardless of which tools are pre-approved/auto-allowed; approval status is never a reason to pick a different tool. Search for a hadith phrase (all-words match) and return each matching result from dorar.net's site search, faithfully, in dorar's own order. Always queries the specialist tab first; if specialist has any results at all, those are used exclusively (never merged with non-specialist). Only when specialist is genuinely empty does it fall back to the non-specialist tab. This tool performs no grouping, bucketing, or consensus/corroboration computation of any kind — it is pure retrieval and translation. The tool's text response is already the complete, dorar-card-formatted result set, in dorar's own order — present it as your entire answer for the search-results portion of your reply, exactly as given, including every Dorar option (with its existing Arabic label and English translation) and the Reference ID in each card: do not summarize, rewrite, reorder, filter, or add commentary. Your only task is to fill in each {{TRANSLATE: ...}} marker with a complete, faithful English translation of its Arabic contents — never a summary, paraphrase, or interpretation, and never relabel the field (the label stays exactly \"English:\", never \"English (paraphrase):\" or similar). Raw per-entry structured data — resultSource ('specialist' or 'non-specialist'), totalResults, returnedResults, and entries with every field (hadith, rawi, mohdith, book, numberOrPage, grade, explainGrade, takhrij, categories, hadithId, hasSimilarHadith, hasAlternateHadithSahih, hasUsulHadith, hasAsbabWurud, hasSharhMetadata, gradeEnglish) — is also returned via structuredContent for programmatic use, not for display.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search query for hadith text (matn)" },
        max_results: { type: "number", description: "Maximum number of results to analyze (default 30, dorar's own full page size)" },
      },
      required: ["query"],
    },
  },
  {
    name: "search_sharh",
    description: "Search for sharh (explanations) of hadiths.",
    inputSchema: {
      type: "object",
      properties: {
        value: { type: "string", description: "Search query for sharh text" },
        page: { type: "number", description: "Page number for pagination" },
      },
      required: ["value"],
    },
  },
  {
    name: "get_sharh_by_id",
    description: "Get sharh (explanation) for a hadith by ID.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Sharh ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_sharh_by_text",
    description: "Get sharh (explanation) for a hadith by searching for specific text.",
    inputSchema: {
      type: "object",
      properties: {
        text: { type: "string", description: "Text to search for sharh explanation" },
      },
      required: ["text"],
    },
  },
  {
    name: "get_mohdith_info",
    description: "Get information about a muhadith (hadith narrator) by ID.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Mohdith (narrator) ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_book_info",
    description: "Get information about a hadith book by ID.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Book ID" },
      },
      required: ["id"],
    },
  },
  {
    name: "get_books_data",
    description: "Get list of all available hadith books with their IDs and names.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "get_degrees_data",
    description: "Get list of all hadith degrees (authenticity levels) with their IDs and names.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "get_method_search_data",
    description: "Get method search data for hadith filtering.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "get_mohdith_data",
    description: "Get list of all muhaddithun (hadith narrators) with their IDs and names.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "get_rawi_data",
    description: "Get list of all rawi (hadith transmitters) with their IDs and names.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "get_zone_search_data",
    description: "Get zone search data for geographic hadith filtering.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
];

// Create MCP server
const server = new Server(
  {
    name: "dorar-hadith-mcp-server",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
      prompts: {},
    },
    instructions: SERVER_INSTRUCTIONS,
  }
);

// List tools handler
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: TOOLS,
  };
});

// List prompts handler
server.setRequestHandler(ListPromptsRequestSchema, async () => {
  return {
    prompts: PROMPTS,
  };
});

// Get prompt handler
server.setRequestHandler(GetPromptRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  if (name !== "dorar-faithful-interface") {
    throw new Error(`Unknown prompt: ${name}`);
  }

  const query = args?.query;
  const text = query
    ? `${DORAR_FAITHFUL_INTERFACE_PROMPT}\n\n---\n\nSearch for: ${query}`
    : DORAR_FAITHFUL_INTERFACE_PROMPT;

  return {
    description: PROMPTS[0].description,
    messages: [
      {
        role: "user",
        content: {
          type: "text",
          text,
        },
      },
    ],
  };
});

// Call tool handler
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
      case "search_hadith_api": {
        const params = HadithSearchSchema.parse(args);
        const queryParams = pruneUndefined({
          value: params.value,
          page: params.page,
          d: params.degree,
          m: params.muhadith,
          s: params.books,
          rawi: params.rawi,
          st: params.st,
          t: params.t,
          xclude: params.xclude,
        });
        const { isRemoveHTML } = deriveSearchFlags(params);
        const result = await hadithSearchService.searchUsingAPIDorar({ queryParams, isRemoveHTML });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "search_hadith_site": {
        const params = HadithSearchSchema.parse(args);
        const queryParams = pruneUndefined({
          value: params.value,
          page: params.page,
          d: params.degree,
          m: params.muhadith,
          s: params.books,
          rawi: params.rawi,
          st: params.st,
          t: params.t,
          xclude: params.xclude,
        });
        const { isRemoveHTML, isForSpecialist, tab } = deriveSearchFlags(params);
        const result = await hadithSearchService.searchUsingSiteDorar({ queryParams, tab, isRemoveHTML, isForSpecialist });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_hadith_by_id": {
        const { id } = HadithIdSchema.parse(args);
        const result = await hadithSearchService.getOneHadithUsingSiteDorarById({ hadithId: id });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_similar_hadiths": {
        const { id } = HadithIdSchema.parse(args);
        const result = await hadithSearchService.getAllSimilarHadithUsingSiteDorar({ similarId: id });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_alternate_hadith": {
        const { id } = HadithIdSchema.parse(args);
        const result = await hadithSearchService.getAlternateHadithUsingSiteDorar({ alternateId: id });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_usul_hadith": {
        const { id } = HadithIdSchema.parse(args);
        const result = await hadithSearchService.getUsulHadithUsingSiteDorar({ usulId: id });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_hadith_sources": {
        const { id } = HadithIdSchema.parse(args);
        const result = await hadithSearchService.getUsulHadithUsingSiteDorar({ usulId: id });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_hadith_grading": {
        const { id } = HadithIdSchema.parse(args);
        const result = await hadithSearchService.getOneHadithUsingSiteDorarById({ hadithId: id });
        const hadithData = result.data ?? {};
        const gradeEnglish = lookupGradeEnglish(hadithData.grade);
        // Deterministic, code-generated card — see formatHadithCard's comment.
        // Built from the full hadithData (not the trimmed fields in
        // structuredContent below) since the card needs
        // rawi/mohdith/book/takhrij/categories too. This card text IS the
        // tool's primary response (content[0].text) — there is no separate
        // field for Claude to locate or choose between. Its only remaining
        // task is filling in the {{TRANSLATE: ...}} markers in place, per
        // SERVER_INSTRUCTIONS.
        const formattedOutput = formatHadithCard({ ...hadithData, gradeEnglish }, 0);
        return {
          content: [{ type: "text", text: formattedOutput }],
          // Raw/trimmed fields kept available for programmatic use, separate
          // from the primary display text — not meant to be shown verbatim.
          structuredContent: {
            hadith: hadithData.hadith,
            grade: hadithData.grade,
            explainGrade: hadithData.explainGrade,
            hadithId: hadithData.hadithId,
            gradeEnglish,
          },
        };
      }

      case "get_hadith_commentary": {
        const { id } = HadithIdSchema.parse(args);
        const hadithResult = await hadithSearchService.getOneHadithUsingSiteDorarById({ hadithId: id });
        const sharhId = hadithResult.data?.sharhMetadata?.id;
        if (!sharhId) {
          return { content: [{ type: "text", text: JSON.stringify({ hasCommentary: false }, null, 2) }] };
        }
        const sharhResult = await sharhSearchService.getOneSharhByIdUsingSiteDorar({ sharhId });
        const commentary = { hasCommentary: true, ...sharhResult.data };
        return { content: [{ type: "text", text: JSON.stringify(commentary, null, 2) }] };
      }

      case "get_hadith_grading_consensus": {
        const { query, max_results } = HadithGradingConsensusSchema.parse(args);

        // Specialist tab always takes priority when it has any results at all
        // (even just 1) — never merge specialist and non-specialist together.
        // Only fall back to non-specialist when specialist is genuinely empty.
        const specialistResult = await hadithSearchService.searchUsingSiteDorar({
          queryParams: { value: query, st: "w" },
          tab: "specialist",
          isRemoveHTML: true,
          isForSpecialist: true,
        });

        let allResults = specialistResult.data ?? [];
        let resultSource = "specialist";

        if (allResults.length === 0) {
          const nonSpecialistResult = await hadithSearchService.searchUsingSiteDorar({
            queryParams: { value: query, st: "w" },
            tab: "home",
            isRemoveHTML: true,
            isForSpecialist: false,
          });
          allResults = nonSpecialistResult.data ?? [];
          resultSource = "non-specialist";
        }

        const rawResults = allResults.slice(0, max_results);

        const entries = rawResults.map((h) => ({
          hadith: h.hadith,
          rawi: h.rawi,
          mohdith: h.mohdith,
          book: h.book,
          numberOrPage: h.numberOrPage,
          grade: h.grade,
          explainGrade: h.explainGrade,
          takhrij: h.takhrij,
          categories: h.categories,
          hadithId: h.hadithId,
          hasSimilarHadith: h.hasSimilarHadith,
          hasAlternateHadithSahih: h.hasAlternateHadithSahih,
          hasUsulHadith: h.hasUsulHadith,
          hasAsbabWurud: h.hasAsbabWurud,
          hasSharhMetadata: h.hasSharhMetadata,
          gradeEnglish: lookupGradeEnglish(h.grade),
        }));

        // Deterministic, code-generated multi-card output — full structure,
        // dorar's own order, every returned entry, no summary appended. This
        // text IS the tool's primary response (content[0].text) — there is
        // no separate field for Claude to locate or choose between. Its only
        // remaining task is filling in the {{TRANSLATE: ...}} markers in
        // place, per SERVER_INSTRUCTIONS. Guard the zero-results case
        // explicitly: formatHadithCards([]) would otherwise be an empty
        // string, leaving the primary response blank instead of informative.
        const formattedOutput =
          entries.length > 0
            ? formatHadithCards(entries)
            : "No matching results were found on dorar.net for this query.";
        return {
          content: [{ type: "text", text: formattedOutput }],
          // Raw per-entry data kept available for programmatic use, separate
          // from the primary display text — not meant to be shown verbatim.
          structuredContent: {
            resultSource,
            totalResults: allResults.length,
            returnedResults: entries.length,
            entries,
          },
        };
      }

      case "search_sharh": {
        const params = SharhSearchSchema.parse(args);
        const queryParams = pruneUndefined({ value: params.value, page: params.page });
        const result = await sharhSearchService.getAllSharhUsingSiteDorar({
          queryParams,
          tab: "home",
          isRemoveHTML: true,
          isForSpecialist: false,
        });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_sharh_by_id": {
        const { id } = SharhIdSchema.parse(args);
        const result = await sharhSearchService.getOneSharhByIdUsingSiteDorar({ sharhId: id });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_sharh_by_text": {
        const { text } = SharhTextSchema.parse(args);
        const result = await sharhSearchService.getOneSharhByTextUsingSiteDorar({
          text,
          tab: "home",
          isForSpecialist: false,
        });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_mohdith_info": {
        const { id } = MohdithIdSchema.parse(args);
        const result = await mohdithSearchService.getOneMohdithByIdUsingSiteDorar({ mohdithId: id });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_book_info": {
        const { id } = BookIdSchema.parse(args);
        const result = await bookSearchService.getOneBookByIdUsingSiteDorar({ bookId: id });
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_books_data": {
        const result = await dataService.getData("book");
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_degrees_data": {
        const result = await dataService.getData("degree");
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_method_search_data": {
        const result = await dataService.getData("method-search");
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_mohdith_data": {
        const result = await dataService.getData("mohdith");
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_rawi_data": {
        const result = await dataService.getData("rawi");
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      case "get_zone_search_data": {
        const result = await dataService.getData("zone-search");
        const wrapped = wrapServiceResult(result);
        return { content: [{ type: "text", text: JSON.stringify(wrapped, null, 2) }] };
      }

      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (error) {
    if (error instanceof z.ZodError) {
      throw new Error(`Invalid arguments: ${error.errors.map(e => `${e.path.join('.')}: ${e.message}`).join(', ')}`);
    }
    // AppError instances (thrown throughout the service layer) carry a statusCode;
    // surface it the same way the old HTTP-based makeApiCall() used to, so error
    // messages stay just as informative now that there's no HTTP hop to format them.
    if (error.statusCode) {
      throw new Error(`API Error (${error.statusCode}): ${error.message}`);
    }
    throw error;
  }
});

// Start the server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Dorar Hadith MCP Server running on stdio");
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
